services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  server:
    build:
      context: ./server
    container_name: linkforge-backend
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    depends_on:
      - redis

  frontend:
    build:
      context: ./link-forge-client
    container_name: linkforge-frontend
    ports:
      - "4200:4200"
    depends_on:
      - server
